(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};ldv=function(t){var e=document.querySelector(t),r=document.querySelector(t+" source"),c=r.getAttribute("data-src");r.setAttribute("src",c),e.play()};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){dpi=window.devicePixelRatio;var a='data-src';var e=document.querySelector('.un31');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/l1000377-1700.jpg':'images/l1000377-850.jpg');
var a='data-src';var e=document.querySelector('.un32');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/dsc01105-828.jpg':'images/dsc01105-414.jpg');
var a='data-src';var e=document.querySelector('.un33');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/dji_0140-1116.jpg':'images/dji_0140-558.jpg');
var a='data-src';var e=document.querySelector('.un34');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/c8585f4a-fdd3-44bf-9447-8b7ee1e07d56-828.jpg':'images/c8585f4a-fdd3-44bf-9447-8b7ee1e07d56-414.jpg');
var a='data-src';var e=document.querySelector('.un35');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/l1000565-550.jpg':'images/l1000565-275.jpg');
var a='data-src';var e=document.querySelector('.un36');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/l1020523-12-1754.jpg':'images/l1020523-12-877.jpg');
var a='data-src';var e=document.querySelector('.un37');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/l1000085-1748.jpg':'images/l1000085-874.jpg');
var a='data-src';var e=document.querySelector('.un38');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/l1010812-1748.jpg':'images/l1010812-874.jpg');
var a='data-src';var e=document.querySelector('.un39');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/dsc00238-734.jpg':'images/dsc00238-367.jpg');
var a='data-src';var e=document.querySelector('.un40');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/177e0ea9-6fe4-4613-8174-e233bde5d3d3-972.jpg':'images/177e0ea9-6fe4-4613-8174-e233bde5d3d3-486.jpg');
var e=document.querySelector('.un28');e.setAttribute('src',(dpi>1)?'images/img_0063-1042.jpeg':'images/img_0063-521.jpeg');
var e=document.querySelector('.un29');e.setAttribute('src',(dpi>1)?'images/img_5892-960.jpg':'images/img_5892-480.jpg');
var e=document.querySelector('.un30');e.setAttribute('src',(dpi>1)?'images/img_0064-566.jpeg':'images/img_0064-283.jpeg');};
if(!window.HTMLPictureElement){r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var l=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));l||(l=1);var n=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];o=(n.getBoundingClientRect().top+pageYOffset)*l}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(t){a||(a=t);var l=t-a;scrollTo(0,r<o?(o-r)*l/400+r:r-(r-o)*l/400),l<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
$('.un41').mouseenter(function() { $.loadImages('images/l1000377-8368.jpg', function() { }) });
$('.un41').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un41-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/l1000377-8368.jpg'; } } });
$('.un43').mouseenter(function() { $.loadImages('images/dsc01105-6000.jpg', function() { }) });
$('.un43').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un43-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/dsc01105-6000.jpg'; } } });
$('.un45').mouseenter(function() { $.loadImages('images/dji_0140-4000.jpg', function() { }) });
$('.un45').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un45-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/dji_0140-4000.jpg'; } } });
$('.un47').mouseenter(function() { $.loadImages('images/c8585f4a-fdd3-44bf-9447-8b7ee1e07d56-4912.jpg', function() { }) });
$('.un47').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un47-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/c8585f4a-fdd3-44bf-9447-8b7ee1e07d56-4912.jpg'; } } });
$('.un49').mouseenter(function() { $.loadImages('images/l1000565-4774.jpg', function() { }) });
$('.un49').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un49-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/l1000565-4774.jpg'; } } });
$('.un51').mouseenter(function() { $.loadImages('images/l1020523-12-8368.jpg', function() { }) });
$('.un51').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un51-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/l1020523-12-8368.jpg'; } } });
$('.un53').mouseenter(function() { $.loadImages('images/l1000085-4272.jpg', function() { }) });
$('.un53').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un53-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/l1000085-4272.jpg'; } } });
$('.un55').mouseenter(function() { $.loadImages('images/l1010812-6804.jpg', function() { }) });
$('.un55').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un55-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/l1010812-6804.jpg'; } } });
$('.un57').mouseenter(function() { $.loadImages('images/dsc00238-1567.jpg', function() { }) });
$('.un57').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un57-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/dsc00238-1567.jpg'; } } });
$('.un59').mouseenter(function() { $.loadImages('images/177e0ea9-6fe4-4613-8174-e233bde5d3d3-6000.jpg', function() { }) });
$('.un59').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un59-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/177e0ea9-6fe4-4613-8174-e233bde5d3d3-6000.jpg'; } } });
$('.un61').mouseenter(function() { $.loadImages('images/img_0063-4032.jpeg', function() { }) });
$('.un61').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un61-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/img_0063-4032.jpeg'; } } });
$('.un62').mouseenter(function() { $.loadImages('images/img_5892-2448.jpg', function() { }) });
$('.un62').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un62-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/img_5892-2448.jpg'; } } });
$('.un63').mouseenter(function() { $.loadImages('images/img_0064-3024.jpeg', function() { }) });
$('.un63').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un63-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/img_0064-3024.jpeg'; } } });
if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un42 source');ldsrcset('.un44 source');ldsrcset('.un46 source');ldsrcset('.un48 source');ldsrcset('.un50 source');ldsrcset('.un52 source');ldsrcset('.un54 source');ldsrcset('.un56 source');ldsrcset('.un58 source');ldsrcset('.un60 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}